### ISSUE TITLE
SmartFile not defined

### ISSUE THREAD

**Issue by thinkinsysdev** [sylvaingi/meteor-smartfile#1]
I added the package using mrt.

Inserted a smartfile.js file and added the SmartFile.configure method.

Started the server, and it crashed stating SmartFile is not defined.

What am I doing wrong?

**Comment by sylvaingi** [comment]
Is this error raised on the server or on the client?

Also, check you have a smartfile/ folder within packages/. If it is not there, check if you are using the latest Meteor and Meteorite, then use `mrt add` again.

**Comment by thinkinsysdev** [comment]
Its happening on both, when i put the configure in /server - i get a server error, then i tried putting it in /client/main.js and i got a client error. Seems like meteor is not recognizing the package - I have installed smartfile using mrt.

**Comment by sylvaingi** [comment]
Can you upload your project on Github so I can try to reproduce your issue?

Sylvain

2013/11/5 tanmay80 notifications@github.com

**Comment by phutschi** [comment]
I have nearly the same problem.
I'm adding the sfInstance.configure method in a smartfile.js

That's the error i'm getting:

Your app is crashing. Here's the latest log.

W202407-22:45:45.006(1)? (STDERR) /Users/otze/Development/experimental/meteor/smartfile_upload/.meteor/local/build/programs/server/boot.js:185
W202407-22:45:45.007(1)? (STDERR) }).run();
W202407-22:45:45.007(1)? (STDERR)    ^
W202407-22:45:45.011(1)? (STDERR) TypeError: Cannot read property 'id' of undefined
W202407-22:45:45.011(1)? (STDERR)     at new SmartFileServer (packages/smartfile/server.js:11)
W202407-22:45:45.011(1)? (STDERR)     at app/smartfile.js:1:53
W202407-22:45:45.012(1)? (STDERR)     at app/smartfile.js:10:3
W202407-22:45:45.012(1)? (STDERR)     at /Users/otze/Development/experimental/meteor/smartfile_upload/.meteor/local/build/programs/server/boot.js:154:10
W202407-22:45:45.012(1)? (STDERR)     at Array.forEach (native)
W202407-22:45:45.012(1)? (STDERR)     at Function._.each._.forEach (/Users/otze/.meteor/tools/0b2f28e18b/lib/node_modules/underscore/underscore.js:79:11)
W202407-22:45:45.012(1)? (STDERR)     at /Users/otze/Development/experimental/meteor/smartfile_upload/.meteor/local/build/programs/server/boot.js:81:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
