### ISSUE TITLE
error, file is not defined in sfInstance.uploads

### ISSUE THREAD

**Issue by sarfrazahmadmca** [sylvaingi/meteor-smartfile#3]
sfInstance.upload(file, {
    fileName: "myupload.jpg", //optional, overrides file.name
    path: "uploads" //optional, path of storage of the upload relative to basePath
}, function (err, res){
    if (err) {
        console.log("upload failed", err);
        return;
    }

```
// Log the public URL of the upload
console.log("Upload public URL:" + sfInstance.resolvePublic(res));
```

});

using this code i am getting error that file is not defined

**Comment by sylvaingi** [comment]
Is file is defined in your code? It must be an instance of File, which you
can obtain through an <input type="file"> element or with drag & drop.

Sylvain

2013/12/27 sarfrazahmadmca notifications@github.com

**Comment by sarfrazahmadmca** [comment]
I wrote all the code in a file name smartfile_config.js. If i write the code at client side it doesn't get the SmartFile instance. or if i write the code at server side i don't get that file instance

**Comment by sarfrazahmadmca** [comment]
Actually I am using redactor plugin to upload the image or to call the method
Template.mc_q_editor.rendered = function () {
$('.editor').redactor({
    imageUpload:"/uploads",
    data:{"file" : $('#redactor').redactor('getObject')},
    imageUploadCallback: function(image, json)
    {
        console.log(json);
       },
    imageUploadErrorCallback: function(json)
    {
        console.log(json.error);
    }
    });
}

 I have wrote all the meteor-smartfile code on server in a file smartfile_config.js. On server it is not getting the file instance. and if I wrote the code at client side, the 'sfInstance.upload' method at client side it doesn't get the 'sfInstance' object at client side

**Comment by sylvaingi** [comment]
Please take a look at https://github.com/sylvaingi/meteor-smartfile-example for how to use this lib
