### ISSUE TITLE
Delete a file

### ISSUE THREAD

**Issue by lfades** [sylvaingi/meteor-smartfile#5]
Hi, first I want to say I am very grateful to be able to upload a file to Smartfile, I'm trying to understand the code in the repository to add new features, I really like help to delete a file while managing to look as file size and other details.

thank you very much.

**Comment by sylvaingi** [comment]
If you want to delete or get file information, use the `rm` or `ls` methods on the server. Are you having issues using those?

**Comment by lfades** [comment]
I had a small problem but I could fix it, thank you very much sylvaingi by the repository.
